lang: java 
before_install:
script:
  - git clone https://github.com/swagger-api/swagger-codegen.git
  - cd swagger-codegen
  - mvn clean install
  - cd ..
  - wget https://raw.githubusercontent.com/gyselroth/tubee/dev/src/lib/Rest/v1/swagger.yml src/swagger.yaml
  - java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i src/swagger.yml -l typescript-node --http-user-agent "tubee typescript-node sdk" -t src -o src --reserved-words-mappings=import=import,class=class
  - npm install
  - npm run build
after_success:
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis CI"
 - git add src/*.ts; git add src/*.yml
 - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
 - git remote add origin-pages https://${GH_TOKEN}@github.com/gyselroth/tubee-sdk-typescript-node.git > /dev/null 2>&1
 - git push --quiet --set-upstream master master
env:
  global:
secure: hZJlqgOzA2zIUJSWIka0PylqNaTkfHq+kS48RrHmocrK0vLyCW7ECWrzez2f2RVdTNzPi0b+yJq2uCbFfWjImZqg+XY1I75/CVVdSYMk7PJkYZ/iBDixMYY8CAkRRd5yZft9uZAdZzR4KLCPN18n7qfISv/M9VA8989NKcVyiEU=
