language: java
jdk:
  - oraclejdk8
arch:
  - ppc64le
before_install:
  - git checkout $TRAVIS_BRANCH
  - git clone https://github.com/swagger-api/swagger-codegen.git
  - cd swagger-codegen
  - git checkout tags/v2.4.14
  - mvn clean install
  - cd ..
script:
  - npm install
  - npm run full-build
after_success:
  - |
    current=$(cat package.json  | grep version: | cat package.json  | grep \"version\" | cut -d'"' -f4)
    new=$(cat swagger.yml | head -n30 | grep 'version: ' | cut -d ':' -f 2 | tr -d ' ' | cut -d '"' -f 2)

    if [ $current != $new ]; then
      sed -i s/\"version\":\ \"$current\"/\"version\":\ \"$new\"/g package.json
      git config --global user.email "aebischer@gyselroth.com"
      git config --global user.name "Travis CI"
      git add src/*.ts; git add src/*.yml
      git add package.json
      git add openapi.yml; git add swagger.yml
      git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
      git push "https://${GH_TOKEN}@github.com/gyselroth/tubee-sdk-typescript-node.git" > /dev/null 2>&1
    fi
env:
  global:
    secure: ebeXOyUTO0Drpf8jp31o9/5yaHAaN3q+mJqGhNkKzVwW5CURiL0qOFhdzTXIqgmVzFE1iHJk+poVX+otYr7NHebKu4iKUQFnxwstY3C25dncI7MpyZRlezse2xdpo9qULhc1W5NA/uvxzCB3DMzo5WxamXBGdDfDGhXfZozT4MV3rC/iq+Fq2xVd2S9apgVztMzToI5iK0es0Sn8WJJO4EbHKvLo7vR8+bpeCLgYZaEC7t9G9uAahMEgFeuGPxdfGd5cTynwdyNpZiU6OueQ9BmRxKO86MIufvcOdXXgeFzjkF+qCenz9Fmx+cU4Cba2nUOID2PcOoCrN8ckAu4qvTo3pODL5/BtRGk3prlULQr0ZEOPYb1claqjEOhxn7BQdTBATvkB/Ovz1DKVkQneK1rLCl8aInRo3QlLJTcxeWMFKCdIbCgvI7kuTLiTqc5HO7qdDhnB92eKIFUaiVeyUSTR338Bher/ZmwAbdPlJdx5lxn9f9mTQl9eKeEjbUUXCcao9p4TgBuAD6Np+X0DAoKvWbGcyF1wx44IyCuTFo0YBT3TST8/GKz2fv+tbFIQ3i5KsFnsWPd0OgSzP+n7DqjMrSiArw8gUTzE2gjk/bvGNkXYWVxt5q9GUs1tpOOMUs70iXuZbulRm79i9bxwLFLhEkSYfJ4Mi6DyH6/61nY=
deploy:
  provider: npm
  email: aebischer@gyselroth.com
  skip_cleanup: true
  api_key:
    secure: OhdZGh4tT0YAhQ28AQ3TFs0emuSYtgBaUCwuYaAAg38RTV+f9/JQhKWlDibfb6/0vZrTn+2ddUL5aZhwOsgb7v27K8zaEbNrPz53LM+LL8MT3xeHMkmytuD0I6mfwnF7KQffmAgBFCyj9CRXLvhT++rNLFqtYk7rl20mB1HgYiJnf92Zk8MWkabwnjYtENPh9K3K7zYilIeTR05w+VB8k00rhs/eFGByoajzqZIjDTGN1BX9P8OlZ+Q/xKrZXAQwXXD56PN5lcWWCX0MarapIHyVfMThN/lXbq9sdvUH9MpdEaAQIwmU/6SpeCJR1GgnRNpsc4zD2EyUeKui8EoVia1JJAzj87r5R/CDiaK/7LHJdINP+3Ra9QOkuZNzyU9TQRBcSt6ke3NRFEhc/Gq0Cn+ZwPwENTXPcRyM9tgWmA1V1Lix/wZVtMjm9jcNggJuKsZCDbw+CfVEZa5cBSjOhPfIewCvKacOVDvNbkqFHOJm/h1uPtCRfHt/wBRNvi49/0dMDxawhK9cW5zKSglFmFqLHcphJCNAxKAvemEG7wjWxY4BB+Q0ZQzD67zaYaTgkq84D+I6yZE6W9ZDOm3BynA2ZYZqFbtcTx7Nw09fJ+c7usEslDYOg42vRC/0oECyUnJKecr1rQ3v8FOOST0uWRxirMTQiAn8DwJNmwE2DpQ=
  on:
    tags: true
    repo: gyselroth/tubee-sdk-typescript-node
