lang: java 
before_install:
script:
  - git clone https://github.com/swagger-api/swagger-codegen.git
  - cd swagger-codegen
  - mvn clean install
  - cd ..
  - java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://raw.githubusercontent.com/gyselroth/tubee/dev/src/lib/Rest/v1/swagger.yml -l typescript-node --http-user-agent "tubee typescript-node sdk" -t . -o .
after_success:
  - .travis/push.sh
env:
  global:
secure: hZJlqgOzA2zIUJSWIka0PylqNaTkfHq+kS48RrHmocrK0vLyCW7ECWrzez2f2RVdTNzPi0b+yJq2uCbFfWjImZqg+XY1I75/CVVdSYMk7PJkYZ/iBDixMYY8CAkRRd5yZft9uZAdZzR4KLCPN18n7qfISv/M9VA8989NKcVyiEU=
